export const AUTH_ACTIONS = {
  START_LOG_IN: 'START_LOG_IN',
  END_LOG_IN: 'END_LOG_IN',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  START_VALIDATING_USER: 'START_VALIDATING_USER',
  END_VALIDATING_USER: 'END_VALIDATING_USER',
};
